Repository penpost/penpost-web, pull requests merged in 2021-04, with the labels that each got.

#16 Jk/styling/variable setup
  .circleci/config.yml
  .gitignore
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  public/index.html
  src/_variables.scss
  src/components/App/App.js
  src/components/App/_App.scss
  src/index.js
  src/index.scss
Labels: documentation, frontend, phase 1, styling

#29 Jk/feature/user landing page
  src/components/App/App.js
  src/components/App/_App.scss
  src/components/User-Landing-Page/User-Landing.js
  src/components/User-Landing-Page/_landing.scss
  src/index.scss
Labels: enhancement, frontend, phase 1

#27 Kb/feature/home component
  package-lock.json
  src/_variables.scss
  src/components/App/App.js
  src/components/App/_App.scss
  src/components/Home/Home.js
  src/components/Home/Home.scss
Labels: phase 1

#28 Gaj/feature/static login
  src/_variables.scss
  src/components/App/App.scss
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/index.js
Labels: enhancement, frontend, phase 1, styling

#31 Gaj/feature/circle ci config
  .circleci/config.yml
Labels: chore, frontend, testing

#35 Jk/feature/update info forms
  .circleci/config.yml
  package-lock.json
  package.json
  src/components/User-Form/Update-Form.js
  src/components/User-Form/_user-form.scss
  src/components/User-Landing-Page/User-Landing.js
  src/components/User-Landing-Page/_landing.scss
  src/index.scss
Labels: enhancement, frontend, phase 1, styling

#39 Create an inital readme user
  README.md
Labels: documentation, phase 2

#42 Kb/feature/error component
  src/components/App/App.js
  src/components/Error/Error.js
  src/components/Error/Error.scss
Labels: enhancement, phase 1

#44 Jk/feature/postcard preview
  .eslintrc.js
  package-lock.json
  package.json
  src/_variables.scss
  src/components/App/App.js
  src/components/App/App.scss
  src/components/Header/_Header.scss
  src/components/Home/Home.js
  src/components/Home/_Home.scss
  src/components/Login/Login.js
  src/components/Login/_Login.scss
  src/components/Postcard-Form/Postcard-Form.js
  src/components/Postcard-Form/_postcard-form.scss
  src/components/Postcard-Preview/Postcard-Preview.js
  src/components/Postcard-Preview/_Postcard-Preview.scss
  src/components/User-Form/Update-Form.js
  src/components/User-Landing-Page/User-Landing.js
  src/components/assets/front-img.jpg
  src/index.scss
Labels: enhancement, frontend, phase 2, styling

#45 Gaj/feature/user flow interactions
  src/components/App/App.js
  src/components/App/_App.scss
  src/components/Error/Error.js
  src/components/Error/_Error.scss
  src/components/Header/Header.js
  src/components/Header/_Header.scss
  src/components/Home/Home.js
  src/components/Home/_Home.scss
  src/components/Login/Login.js
  src/components/Login/_Login.scss
  src/components/Postcard-Form/Postcard-Form.js
  src/components/Postcard-Form/_Postcard-Form.scss
  src/components/Postcard-Form/_postcard-form.scss
  src/components/Postcard-Preview/Postcard-Preview.js
  src/components/Update-Form/Update-Form.js
  src/components/Update-Form/_Update-Form.scss
  src/components/User-Landing/User-Landing.js
  src/components/User-Landing/_User-Landing.scss
  src/components/assets/postage-stamp.png
  src/index.scss
Labels: enhancement, frontend, phase 2, styling

#51 Jk/feature/apollo setup
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/components/App/App.js
  src/components/Login/Login.js
  src/components/User-Landing/User-Landing.js
  src/index.js
Labels: enhancement, frontend, phase 3

#53 Gaj/fix/create baseline
  src/GraphQL/queries.js
  src/components/App/App.js
  src/components/Error/Error.js
  src/components/Login/Login.js
  src/components/Postcard-Form/Postcard-Form.js
  src/components/Postcard-Preview/Postcard-Preview.js
  src/components/Update-Form/Update-Form.js
  src/components/User-Landing/User-Landing.js
  src/index.js
Labels: chore, frontend, refactor

#54 Jk/feature/apollo mutations
  cypress/integration/test.js
  cypress/screenshots/test.js/Logging In -- Should greet the user & describe app (failed).png
  cypress/videos/test.js.mp4
  src/GraphQL/update-user.js
  src/components/Update-Form/Update-Form.js
  src/components/User-Landing/User-Landing.js
  src/index.js
Labels: enhancement, frontend, phase 3, refactor

#55 Gaj/fix/yml
  .circleci/config.yml
  package.json
  src/components/Postcard-Form/Postcard-Form.js
Labels: chore, frontend

#56 Jk/feature/local storage
  src/GraphQL/signin-user.js
  src/GraphQL/update-user.js
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Login/Login.js
  src/components/Update-Form/Update-Form.js
  src/components/User-Landing/User-Landing.js
Labels: enhancement, frontend, phase 3

#59 Gaj/testing/unstubbed components
  cypress/integration/CreatePostcard_spec.js
  cypress/integration/Home_spec.js
  cypress/integration/Login_spec.js
  cypress/integration/UserLanding_spec.js
  cypress/integration/test.js
  package-lock.json
  package.json
  src/GraphQL/mutations.js
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Home/Home.js
  src/components/Home/_Home.scss
  src/components/Login/Login.js
  src/components/Postcard-Form/Postcard-Form.js
  src/components/Update-Form/Update-Form.js
  src/components/User-Landing/User-Landing.js
Labels: bug, frontend, phase 3, testing

#60 Jk/bugfix/landing query
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Home/_Home.scss
  src/components/Login/Login.js
Labels: bug
